- draft-dekater-scion-controlplane.md
This is my proposal to address the scion/BGP AS number objection.
Fixes #9
> Declare SCION AS numbers independant from BGP ASNs.

- draft-dekater-scion-controlplane.md
There's still some more MUST required IMHO.
> Improve references classification and uses of MUST and SHOULD

- draft-dekater-scion-controlplane.md
Contributes to #17 (by virtue of avoiding the phrase "peering AS").
> Introduce motivation for link types, explain restrictions for peering links

- draft-dekater-scion-controlplane.md
> Move informative references to the informative section. Delete un-used ones

- draft-dekater-scion-controlplane.md
Introduction with problem statement and component overview
> Added revised Introduction

- draft-dekater-scion-controlplane.md
Resolves https://github.com/scionassociation/scion-dp_I-D/issues/11
> remove allowed

- draft-dekater-scion-controlplane.md
> clarify path reversibility

- draft-dekater-scion-controlplane.md
Have not changed this in code references
Solves #12
> Highlighted use of MUST, MUST NOT and SHOULD where appropriate.

- draft-dekater-scion-controlplane.md
> Clarify beaconing fast retry at bootstrapping

- draft-dekater-scion-controlplane.md
> grpc: describe empty responses and mention the existence of gRPC errors

- draft-dekater-scion-controlplane.md
> Updated Intro and add changelog

- draft-dekater-scion-controlplane.md
> cp_draft: fix recommended/typical values for best PCB set size and AS cert TTL

- draft-dekater-scion-controlplane.md
Resolves #19 
Contributes to #58
> General review - nico

- draft-dekater-scion-controlplane.md
> addressing: clarify text representation

- draft-dekater-scion-controlplane.md
> add section about monitoring the CP

- draft-dekater-scion-controlplane.md
> add section about monitoring the CP (continued)

- draft-dekater-scion-controlplane.md
> Intro: precise wording (feedback D. Galan)

- draft-dekater-scion-controlplane.md
> Terminology: PCB wording

- draft-dekater-scion-controlplane.md
> api: add the trust metrials API

- draft-dekater-scion-controlplane.md
> PCB policies: add wording by Daniel Galan

- .gitignore
- draft-dekater-scion-controlplane.md
Fixes #89 
Draft [diff to main](https://author-tools.ietf.org/api/iddiff?url_1=https://scionassociation.github.io/scion-cp_I-D/draft-dekater-scion-controlplane.txt&url_2=https://scionassociation.github.io/scion-cp_I-D/Security-Updates/draft-dekater-scion-controlplane.txt)
> Security considerations: clarify assumptions and security properties

- draft-dekater-scion-controlplane.md
Resolves #100 
Draft [diff](https://author-tools.ietf.org/api/iddiff?url_1=https://scionassociation.github.io/scion-cp_I-D/draft-dekater-scion-controlplane.txt&url_2=https://scionassociation.github.io/scion-cp_I-D/beaconing-reorg/draft-dekater-scion-controlplane.txt)
> Beaconing: reorganize paragraph 2.3
